name: Submit Dependencies Without Restore (NuGet)

on:
  workflow_dispatch:       # Allows manual triggering

jobs:
  submit-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'  # Or match your project

      - name: Submit NuGet dependencies (no restore)
        uses: github/dependency-submission-action@v1
        with:
          use-dotnet-project-files: true
