name: 'Dependency Review'
on:
  schedule:
    - cron: '0 3 * * 1'   # Every Monday at 3 AM UTC
  workflow_dispatch:      # Allow manual trigger

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v4
