name: Validate Package Version Alignment

on:
  push:
    branches:
      - main
    paths:
      - '**/Directory.Packages.props'

  workflow_dispatch: {}

jobs:
  validate-package-alignment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Validate that package versions are aligned across Directory.Packages.props files
        shell: pwsh
        run: ./.github/scripts/validate-package-version-alignment.ps1
          
