name: Validate Unused NuGet Packages

on:
  workflow_dispatch:  # Manual trigger

jobs:
  validate-unused-packages:
    name: Detect Unused Packages in Directory.Packages.props
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Scan for unused packages
        shell: pwsh
        run: ./.github/scripts/validate-unused-packages.ps1
