name: Validate Projects' Directory.Packages.props

on:
  push:
    branches:
      - main
    paths:
      - '**/Directory.Packages.props'
      - '!Directory.Packages.props'  # Exclude the root-level file											  

  workflow_dispatch:
    inputs:
      usageThreshold:
        description: 'Maximum number of project-level props files a package can appear in before it is considered a violation'
        required: false
        default: '2'

jobs:
  validate-project-level-packages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate Projects' Directory.Packages.props usage
        shell: pwsh
        run: ./.github/scripts/validate-projects-directory-packages-props.ps1 -UsageThreshold ${{ inputs.usageThreshold }}
